# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/MinhTrieu/python-app/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 595)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(790, 60, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 110, 63, 20))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 50, 63, 20))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 60, 381, 381))
        self.label_5.setMidLineWidth(2)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/MinhTrieu/python-app/ui/../img/image.webp"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.txt_email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_email.setEnabled(True)
        self.txt_email.setGeometry(QtCore.QRect(20, 240, 331, 51))
        self.txt_email.setStatusTip("")
        self.txt_email.setStyleSheet("\n"
"        border: 2px solid #3498db;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"        font-size: 16px;\n"
"        background-color: #ecf0f1;\n"
"        color: #2c3e50;")
        self.txt_email.setInputMask("")
        self.txt_email.setCursorPosition(0)
        self.txt_email.setObjectName("txt_email")
        self.txt_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_password.setGeometry(QtCore.QRect(20, 300, 331, 51))
        self.txt_password.setStyleSheet("\n"
"        border: 2px solid #3498db;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"        font-size: 16px;\n"
"        background-color: #ecf0f1;\n"
"        color: #2c3e50;")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(100, 360, 161, 51))
        self.btn_login.setStyleSheet("\n"
"        background-color: #e74c3c;\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"        border: 2px solid #c0392b;\n"
"        transition: 0.3s;\n"
"        background-color: #c0392b;\n"
"        border: 2px solid #a93226;\n"
"    \n"
"        background-color: #922b21;\n"
"        border: 2px solid #7b241c;")
        self.btn_login.setObjectName("btn_login")
        self.btn_register = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(140, 420, 93, 21))
        self.btn_register.setObjectName("btn_register")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 30, 191, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/MinhTrieu/python-app/ui/../img/image003.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 801, 531))
        self.label_3.setStyleSheet("background:rgb(255, 255, 255);\n"
"color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.btn_eye_p = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_eye_p.setGeometry(QtCore.QRect(310, 320, 31, 21))
        self.btn_eye_p.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/MinhTrieu/python-app/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_p.setIcon(icon)
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.label_3.raise_()
        self.frame.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.txt_email.raise_()
        self.txt_password.raise_()
        self.btn_login.raise_()
        self.btn_register.raise_()
        self.label_2.raise_()
        self.btn_eye_p.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "email"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.btn_register.setText(_translate("MainWindow", "register"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
